name: RelativeCI

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: hmarr/debug-action@v3

      - name: Send bundle stats and build information to RelativeCI
        uses: relative-ci/agent-action@v2.2.0
        with:
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
